USE SPortalDb

GO 
CREATE TABLE PostType(
PostTypeID INT PRIMARY KEY IDENTITY(1,1),
Type VARCHAR(30) -- PARENT OR CHILD POST
)

GO
CREATE TABLE Post(
PostID INT PRIMARY KEY IDENTITY(1,1),
CommentID INT FOREIGN KEY (PostID) REFERENCES Post (PostID),
Text VARCHAR(MAX),
UserID INT FOREIGN KEY(UserID) REFERENCES Users(UserID),
Upvotes SMALLINT,
DownVotes SMALLINT,
SubmissionDate DATETIME2
)

GO 
CREATE TABLE Topic(
TopicID INT PRIMARY KEY IDENTITY(1,1),
TopicName VARCHAR(30),
TopicDescription VARCHAR(100),
CreationDate DATETIME2
)

GO 
CREATE TABLE TopicPost(
TPID INT PRIMARY KEY IDENTITY(1,1),
TopicID INT FOREIGN KEY (TopicID) REFERENCES Topic (TopicID),
PostID INT FOREIGN KEY (PostID) REFERENCES Post (PostID)
)