USE SPortalDb
GO

CREATE TABLE Division(
DivisionID INT PRIMARY KEY IDENTITY(1,1),
DivisionName VARCHAR(30),
)

GO 
CREATE TABLE Post(
PostID INT PRIMARY KEY IDENTITY(1,1),
DivisionID INT FOREIGN KEY(DivisionID) REFERENCES Division(DivisionID),
Creator INT FOREIGN KEY (Creator) REFERENCES UserDetails(UserID)NOT NULL, 
Title VARCHAR(30)NOT NULL,
PostDate DATETIME NOT NULL,
Rating INT
)

GO
CREATE TABLE WikiEntry(
EntryID INT PRIMARY KEY IDENTITY(1,1),
PostID INT FOREIGN KEY(PostID) REFERENCES Post(PostID),
ValidationDate DATETIME
)