USE SPortalDb
GO

CREATE PARTITION FUNCTION pfRecordsRange(INT)
AS
RANGE LEFT FOR VALUES (10000, 50000, 100000)

GO
CREATE PARTITION FUNCTION pfOrderDateRange(DATETIME2)
AS
RANGE LEFT FOR VALUES ('2014/10/30', '2015/10/30', '2016/10/30')

GO
CREATE PARTITION SCHEME psOrderDateRange
AS
PARTITION pfOrderDateRange TO (Partition1, Parttion2)

GO
ALTER TABLE Post
CONSTRAINT PostID PRIMARY KEY CLUSTERED (UserID ASC, Submissiondate ASC)
ON pdOrderDateRange(SubmissionDate)


