USE SportalDb 

GO
CREATE TABLE StatusType(
	STID INT PRIMARY KEY IDENTITY(1,1),
	Name VARCHAR(30)
)

GO
CREATE TABLE ConversationInstance(
	ConversationID INT PRIMARY KEY IDENTITY(1,1),
	UserOne INT FOREIGN KEY(UserOne) REFERENCES Users(UserID)NOT NULL,
	UserTwo INT FOREIGN KEY(UserTwo) REFERENCES Users(UserID) NOT NULL,
	IP VARCHAR(100) NOT NULL,
	TimeSent DATETIME2 NOT NULL,
	ChatStatus INT INT FOREIGN KEY (ChatStatus) REFERENCES StatusType(STID)
)

GO 
CREATE TABLE CoversationReply(
	CRID INT PRIMARY KEY IDENTITY(1,1),
	CID INT FOREIGN KEY(CID) REFERENCES ConversationInstance(ConversationID) NOT NULL,
	Reply TEXT NOT NULL,
	IP VARCHAR(100) NOT NULL,
	TimeSent DATETIME2 NOT NULL,
	ReplyStatus INT FOREIGN KEY (ReplyStatus) REFERENCES StatusType(STID)
)



GO
CREATE TABLE Friends(
	RelationID INT PRIMARY KEY IDENTITY(1,1),
	MeID INT FOREIGN KEY(MeID) REFERENCES Users(UserID),
	FriendID INT FOREIGN KEY(FriendID) REFERENCES Users(UserID)
)