USE SPortalDb
GO
CREATE MASTER KEY ENCRYPTION BY PASSWORD = '#AdMiN@lOgIn^2013*SP#ortal'

USE SportalDb
BACKUP MASTER KEY TO FILE = 'C:\\inetpub\wwwroot\SPortalDbSubscriber'
ENCRYPTION BY PASSWORD = 'AdMiNlOgIn2013SPortalb'

USE SPortalDb
CREATE CERTIFICATE TDECert
WITH SUBJECT = 'TDE Certificate'
GO

USE SPortalDb
CREATE DATABASE ENCRYPTION KEY
WITH ALGORITHM = AES_256
ENCRYPTION BY SERVER CERTIFICATE TDECert
GO

ALTER DATABASE SportalDb
SET ENCRYPTION ON
GO

