GO
:r "C:\Database Scripts\Create Tables\1 - Institution.sql"
:r "C:\Database Scripts\Create Tables\2 - PostType.sql"
:r "C:\Database Scripts\Create Tables\3 - UserType.sql"
:r "C:\Database Scripts\Create Tables\3.1 - Users.sql"
:r "C:\Database Scripts\Create Tables\4 - MemberRole.sql"
:r "C:\Database Scripts\Create Tables\5 - TopicType.sql"
:r "C:\Database Scripts\Create Tables\6 - Topic.sql"
:r "C:\Database Scripts\Create Tables\6.1 - TopicUsers.sql"
:r "C:\Database Scripts\Create Tables\6.2 - TopicVotes.sql"
:r "C:\Database Scripts\Create Tables\7 - Group.sql"
:r "C:\Database Scripts\Create Tables\7.1 - UserGroup.sql"
:r "C:\Database Scripts\Create Tables\8 - Post.sql"
:r "C:\Database Scripts\Create Tables\8.1 - PostUsers.sql"
:r "C:\Database Scripts\Create Tables\8.2 - PostVotes.sql"
:r "C:\Database Scripts\Create Tables\9 - GroupInvites.sql"
:r "C:\Database Scripts\Create Tables\10 - InstitutionInvites.sql"