GO
:r "C:\Database Scripts\Create Procedures\AddGroupMember.sql"
:r "C:\Database Scripts\Create Procedures\CreateGroup.sql"
:r "C:\Database Scripts\Create Procedures\CreatePost.sql"
:r "C:\Database Scripts\Create Procedures\LoginUser.sql"
:r "C:\Database Scripts\Create Procedures\RegisterUser.sql"
:r "C:\Database Scripts\Create Procedures\SelectGroupByGroupName.sql"
:r "C:\Database Scripts\Create Procedures\SelectGroupByUsername.sql"
:r "C:\Database Scripts\Create Procedures\SelectPostByPostID.sql"
:r "C:\Database Scripts\Create Procedures\SelectPostsByUser.sql"
:r "C:\Database Scripts\Create Procedures\SelectPostRating.sql"

:r "C:\Database Scripts\Create Procedures\SelectPostsByTopicID.sql"
:r "C:\Database Scripts\Create Procedures\SelectPostTopicName.sql"
:r "C:\Database Scripts\Create Procedures\SelectTopicByID.sql"
:r "C:\Database Scripts\Create Procedures\SelectTopicByName.sql"
:r "C:\Database Scripts\Create Procedures\SelectTopicRepliesAmount.sql"
:r "C:\Database Scripts\Create Procedures\SelectTopics.sql"
:r "C:\Database Scripts\Create Procedures\SelectUserInfo.sql"
:r "C:\Database Scripts\Create Procedures\SelectUserPostsAmount.sql"
:r "C:\Database Scripts\Create Procedures\SelectUsersByInstitution.sql"
:r "C:\Database Scripts\Create Procedures\SelectUserType.sql"

:r "C:\Database Scripts\Create Procedures\Upvote.sql"
:r "C:\Database Scripts\Create Procedures\Downvote.sql"
:r "C:\Database Scripts\Create Procedures\UpdateUser.sql"
:r "C:\Database Scripts\Create Procedures\CreateTopic.sql"
:r "C:\Database Scripts\Create Procedures\CreatePostReply.sql"
:r "C:\Database Scripts\Create Procedures\SelectPostReplies.sql"
:r "C:\Database Scripts\Create Procedures\SelectUserTopicsAmount.sql"
:r "C:\Database Scripts\Create Procedures\SelectEmails.sql"
:r "C:\Database Scripts\Create Procedures\SelectDownvotes.sql"
:r "C:\Database Scripts\Create Procedures\SelectUpvotes.sql"

:r "C:\Database Scripts\Create Procedures\InsertGroupInvite.sql"
:r "C:\Database Scripts\Create Procedures\RemoveGroupMember.sql"
:r "C:\Database Scripts\Create Procedures\DeleteGroup.sql"
:r "C:\Database Scripts\Create Procedures\UpdateGroup.sql"
:r "C:\Database Scripts\Create Procedures\UpdatePost.sql"
:r "C:\Database Scripts\Create Procedures\SelectGroups.sql"
:r "C:\Database Scripts\Create Procedures\CreateInstitution.sql"
:r "C:\Database Scripts\Create Procedures\SelectInstitutions.sql"
:r "C:\Database Scripts\Create Procedures\AcceptInstitutionRequest.sql"
:r "C:\Database Scripts\Create Procedures\LeaveInstitution.sql"
:r "C:\Database Scripts\Create Procedures\SelectUserPicture.sql"