GO
:r "C:\Database Scripts\Create Tables\1 - Institution.sql"
:r "C:\Database Scripts\Create Tables\2 - PostType.sql"
:r "C:\Database Scripts\Create Tables\3 - UserType.sql"
:r "C:\Database Scripts\Create Tables\3.1 - Users.sql"
:r "C:\Database Scripts\Create Tables\4 - Group.sql"
:r "C:\Database Scripts\Create Tables\5 - MemberRole.sql"
:r "C:\Database Scripts\Create Tables\6 - UserGroup.sql"
:r "C:\Database Scripts\Create Tables\7 - Post.sql"
:r "C:\Database Scripts\Create Tables\7.1 - PostUsers.sql"
:r "C:\Database Scripts\Create Tables\7.2 - PostVotes.sql"
:r "C:\Database Scripts\Create Tables\8 - TopicType.sql"
:r "C:\Database Scripts\Create Tables\8.1 - Topic.sql"
:r "C:\Database Scripts\Create Tables\8.2 - TopicVotes.sql"

