GO
:r "C:\Database Scripts\Create Tables\1 - Institution.sql"
:r "C:\Database Scripts\Create Tables\2 - PostType.sql"
:r "C:\Database Scripts\Create Tables\3 - UserType.sql"
:r "C:\Database Scripts\Create Tables\3.1 - Users.sql"
:r "C:\Database Scripts\Create Tables\4 - GroupHouse.sql"
:r "C:\Database Scripts\Create Tables\5 - MemberRole.sql"
:r "C:\Database Scripts\Create Tables\6 - GroupMembers.sql"
:r "C:\Database Scripts\Create Tables\7 - Post.sql"
:r "C:\Database Scripts\Create Tables\8 - Topic.sql"
:r "C:\Database Scripts\Create Tables\8.1 - TopicType.sql"
:r "C:\Database Scripts\Create Tables\9 - Topic Post.sql"
:r "C:\Database Scripts\Create Tables\10 - PostViews.sql"